### ISSUE TITLE
Versioning example year mismatch

### ISSUE THREAD

**Issue by TeFiLeDo** [onlyf1com/onlyf1-db#20]
There seems to be a mismatch between the version and explanation years in the versioning example.

What is there vs. what I'd expect:
- **2023.0.0.alpha** – Pre-season alpha release before the 1<sup>st</sup> race round of the 2022 season.
- **2023.0.0.alpha** – Pre-season alpha release before the 1<sup>st</sup> race round of the 2023 season.

**Comment by marceloverdijk** [comment]
Hi @TeFiLeDo thanks for reaching out.
I'm not sure what the problem is you are facing, could you maybe eloborate?

**Comment by TeFiLeDo** [comment]
Hi @marceloverdijk. I'm not really facing any problem, however I believe that there is a mistake in the versioning section of the `README.md` file. It lists several examples of what a specific version number means. I think that there is a mismatch between the version numbers (2023) and the explanations (2022).

Example:
```md
<!-- current text -->
- **2023.0.0.alpha** – Pre-season alpha release before the 1<sup>st</sup> race round of the 2022 season.

<!-- what I believe is meant, notice the year at the end -->
- **2023.0.0.alpha** – Pre-season alpha release before the 1<sup>st</sup> race round of the 2023 season.
```

**Comment by marceloverdijk** [comment]
Ah I see, good catch 👍

**Comment by marceloverdijk** [comment]
Fixed and thanks again 👍
